server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/miniblog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    #    hibernate.hbm2ddl.auto: create-drop
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #      show_sql: true
        format_sql: true
        use_sql_comments: true
logging.level:
    org.hibernate.SQL: debug